trigger:
- main # Replace 'main' with your branch name

pool:
  vmImage: 'ubuntu-latest' # Use macos-latest only if necessary for your build

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '' # Leave empty if gradlew is in the repository root
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true # Set to true if you want to publish test results
    testResultsFiles: '**/TEST-*.xml' # Specify test result patterns only if applicable
    tasks: 'assembleDebug' # Adjust Gradle task based on your build requirements
